class_name Params extends RefCounted


const GRAVITY = 750
const TERM_VEL = 250

const PLAYER_MAX_VEL = 85
const PLAYER_JUMP_VEL = 310
const PLAYER_AIR_ACCEL = 10
const PLAYER_AIR_DECEL = 5
const PLAYER_VARIABLE_JUMP_MARGIN = 0.2
const PLAYER_COYOTE_MARGIN = 0.15
const PLAYER_HAZARD_THROWBACK_VEL = 600

#const ENEMY_FREEZE_TIME = 5.0
#const ENEMY_RESPAWN_DELAY = 5
#const ENEMY_RESPAWN_DISTANCE = 32

const MIN_DISTANCE_RESPAWN = 128
const SLIME_WALK_VEL = 25

const TROOPER_WALK_VEL = 30
const TROOPER_CHASE_VEL = 75



